AdminConfigScreen As screen:

    TextInput1 As text:
        Default: =""
        X: =36
        Y: =92
        ZIndex: =1

    Label1 As label:
        FontWeight: =Bold
        Text: ="Data Color 1"
        X: =40
        Y: =40
        ZIndex: =2

    TextInput1_1 As text:
        Default: =""
        X: =36
        Y: =214
        ZIndex: =3

    Label1_1 As label:
        FontWeight: =Bold
        Text: ="Data Color 2"
        X: =40
        Y: =162
        ZIndex: =4

    TextInput1_2 As text:
        Default: =""
        X: =36
        Y: =340
        ZIndex: =5

    Label1_2 As label:
        FontWeight: =Bold
        Text: ="Data Color 3"
        X: =40
        Y: =288
        ZIndex: =6

    TextInput1_3 As text:
        Default: =""
        X: =36
        Y: =470
        ZIndex: =7

    Label1_3 As label:
        FontWeight: =Bold
        Text: ="Data Color 4"
        X: =40
        Y: =418
        ZIndex: =8

    TextInput1_4 As text:
        Default: =""
        X: =36
        Y: =605
        ZIndex: =9

    Label1_4 As label:
        FontWeight: =Bold
        Text: ="Data Color 5"
        X: =40
        Y: =553
        ZIndex: =10

    Circle1 As circle:
        BorderThickness: =1
        Fill: =ColorValue(TextInput1.Text)
        Height: =57
        Width: =60
        X: =395
        Y: =83
        ZIndex: =11

    Button1 As button:
        Fill: =RGBA(54, 176, 75, 1)
        OnSelect: |-
            =ClearCollect(colorscheme, {Färg1: TextInput1.Text, Färg2: TextInput1_1.Text, Färg3: TextInput1_2.Text, Färg4: TextInput1_3.Text, Färg5:TextInput1_4.Text})
        Size: =10
        Text: ="Skapa färgschema"
        X: =116
        Y: =688
        ZIndex: =12

    Circle1_1 As circle:
        BorderThickness: =1
        Fill: =ColorValue(TextInput1_1.Text)
        Height: =57
        Width: =60
        X: =395
        Y: =207
        ZIndex: =13

    Circle1_2 As circle:
        BorderThickness: =1
        Fill: =ColorValue(TextInput1_2.Text)
        Height: =57
        Width: =60
        X: =395
        Y: =328
        ZIndex: =14

    Circle1_3 As circle:
        BorderThickness: =1
        Fill: =ColorValue(TextInput1_3.Text)
        Height: =57
        Width: =60
        X: =395
        Y: =458
        ZIndex: =15

    Circle1_4 As circle:
        BorderThickness: =1
        Fill: =ColorValue(TextInput1_4.Text)
        Height: =57
        Width: =60
        X: =395
        Y: =596
        ZIndex: =16

    TextInput2 As text:
        Default: =
        Height: =102
        Mode: =TextMode.MultiLine
        Width: =685
        X: =529
        Y: =586
        ZIndex: =17

    Label2 As label:
        FontWeight: =Bold
        Height: =58
        Text: ="Klistra in nedan i App - > OnStart"
        Width: =331
        X: =529
        Y: =528
        ZIndex: =18

    Button1_1 As button:
        Fill: =RGBA(54, 176, 75, 1)
        OnSelect: |-
            =ClearCollect(colorscheme, {Färg1: "#527138", Färg2: "#07060B", Färg3: "#FFFFFF",  Färg4: "#CACACA", Färg5:"#D32B2B"})
        Size: =10
        Text: ="Skapa färgschema"
        X: =295
        Y: =688
        ZIndex: =19

